version: '3'
networks:
  access-bridge:
    driver: bridge
  application-bridge:
    driver: bridge
services:
  ejbca-database:
    container_name: ejbca-database
    image: "library/mariadb:latest"
    networks:
      - application-bridge
    environment:
      - MYSQL_DATABASE=ejbca
      - MYSQL_USER=ejbca
      - MYSQL_PASSWORD=/run/secrets/ejbca-mysql-password
      - MYSQL_ROOT_PASSWORD=/run/secrets/ejbca-root-password
    secrets:
      - ejbca-mysql-password
      - ejbca-root-password
    volumes:
      - ejbcadb:/var/lib/mysql:rw
    restart: always
  ejbca-node1:
    hostname: ejbca-node1
    container_name: ejbca
    image: keyfactor/ejbca-ce:latest
    depends_on:
      - ejbca-database
    networks:
      - access-bridge
      - application-bridge
    environment:
      - DATABASE_JDBC_URL=jdbc:mariadb://ejbca-database:3306/ejbca?characterEncoding=UTF-8
      - LOG_LEVEL_APP=INFO
      - LOG_LEVEL_SERVER=INFO
      - TLS_SETUP_ENABLED=simple
      - DATABASE_PASSWORD=/run/secrets/ejbca-mysql-password
    secrets:
      - ejbca-mysql-password
    ports:
      - "80:8080"
      - "443:8443"
    restart: always

volumes:
  ejbcadb:

secrets:
  ejbca-root-password:
    file: ./ejbca-root-password.txt
  ejbca-mysql-password:
    file: ./ejbca-mysql-password.txt
