version: "3"

networks:
  gitea:

services:
  server:
    image: gitea/gitea:latest
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=/run/secrets/gitea_postgres_password
    secrets:
      - gitea_postgres_password
    networks:
      - gitea
    volumes:
      - gitea_gitea-server:/data
    ports:
      - "192.168.178.152:4300:3000"
      - "192.168.178.152:4322:22"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=/run/secrets/gitea_postgres_password
      - POSTGRES_DB=gitea
    secrets:
      - gitea_postgres_password
    networks:
      - gitea
    volumes:
      - gitea_gitea-postgres:/var/lib/postgresql/data

volumes:
  gitea_gitea-server:
    external: true
  gitea_gitea-postgres:
    external: true

secrets:
  gitea_postgres_password:
    file: ./gitea_postgres_password.txt
